@echo off
echo Preparing to commit changes (including file deletions)...
git add --all
echo Committing changes...
git commit -m "Remove files that no longer exist locally"
echo Pushing to GitHub...
git push origin master
echo Displaying the most recent commit...
git log -1
echo Operation completed!
pause